/*
 * Copyright 2006, Realtek Semiconductor Corp.
 *
 *   RTL8685 chip-level header file
 *
 * Tony Wu (tonywu@realtek.com.tw)
 * Nov. 07, 2006
 */
#ifndef _BSPCHIP_H_
#define _BSPCHIP_H_

#define BONDING_REG	(0xBB0001E8)
#define STRAPING_REG	(0xBB0001EC)
#define BONDING_REG_DRAMTYPE_FREQ43_FD_S	(5)
#define BONDING_REG_DRAMTYPE_FREQ43_MASK	(3 << BONDING_REG_DRAMTYPE_FREQ43_FD_S)
#define STRAPING_REG_DRAMTYPE_FREQ210_FD_S	(22)
#define STRAPING_REG_DRAMTYPE_FREQ210_MASK	(7 << STRAPING_REG_DRAMTYPE_FREQ210_FD_S)

/* System registers */
#define SYSREG_SYSTEM_STATUS_REG	(0xB8000044)
#define SYSREG_PIN_STATUS_REG		(0xB8000100)
	#define CONFIG_RTL8685_25M_XTAL
#define SYSREG_PINMUX0_REG			(0xB8000108)
#define SYSREG_PLL_CTL_REG			(0xB8000214)
#define SYSREG_LX_PLL_SEL_REG		(0xB8000228)
#define SYSREG_DRAM_CLK_EN_REG		(0xB800022c)
#define SYSREG_SYSCLK_CONTROL_REG	(0xB8000200)
#define SYSREG_MCKG_PHS_SEL_REG		(0xB8000220)
#define SYSREG_MCKG_FREQ_DIV_REG	(0xB8000224)
#define SYSREG_IP_EN_CTL_REG	        (0xB8000600)
#define SYSREG_ANA1_CTL_REG        	(0xB8000218)
#if defined(CONFIG_RTL8685S) || defined(CONFIG_RTL8685SB)
#define SYSREG_SYSTEM_STATUS_CF_CKSE_LX_FD_S (4)
#define SYSREG_SYSTEM_STATUS_CF_CKSE_LX_MASK (1 << SYSREG_SYSTEM_STATUS_CF_CKSE_LX_FD_S)
#define SYSREG_SYSTEM_STATUS_CF_CKSE_LX_LXPLL SYSREG_SYSTEM_STATUS_CF_CKSE_LX_MASK
#endif /* CONFIG_RTL8685 */
#define SYSREG_SYSTEM_STATUS_SYS_CPU2_EN_S 		(5)
#define SYSREG_SYSTEM_STATUS_SYS_CPU2_EN_MASK 	(1 << SYSREG_SYSTEM_STATUS_SYS_CPU2_EN_S)
#define SYSREG_SYSTEM_STATUS_CF_CKSE_OCP0_FD_S (2)
#define SYSREG_SYSTEM_STATUS_CF_CKSE_OCP0_MASK (1 << SYSREG_SYSTEM_STATUS_CF_CKSE_OCP0_FD_S)
#define SYSREG_SYSTEM_STATUS_CF_CKSE_OCP0_OCP0PLL SYSREG_SYSTEM_STATUS_CF_CKSE_OCP0_MASK
#define SYSREG_SYSTEM_STATUS_CF_CKSE_OCP0_LXPLL (0 << SYSREG_SYSTEM_STATUS_CF_CKSE_OCP0_FD_S)

#define SYSREG_PIN_STATUS_CKSEL_FD_S	(5)
#define SYSREG_PIN_STATUS_CKSEL_25MHZ	(0)
#define SYSREG_PIN_STATUS_CKSEL_40MHZ	(1)
#define SYSREG_PIN_STATUS_CKSEL_MASK	(1 << SYSREG_PIN_STATUS_CKSEL_FD_S)
#if defined(CONFIG_RTL8685S) || defined(CONFIG_RTL8685SB)
#define SYSREG_LX_PLL_CTRL_LXPLL_FD_S	(0)
#define SYSREG_LX_PLL_CTRL_LXPLL_FD_MASK	(0xf << SYSREG_LX_PLL_CTRL_LXPLL_FD_S)
#define SYSREG_LX_PLL_CTRL_SPIFPLL_FD_S	(8)
#define SYSREG_LX_PLL_CTRL_SPIFPLL_FD_MASK	(0xf << SYSREG_LX_PLL_CTRL_SPIFPLL_FD_S)
#endif /* CONFIG_RTL8685S */
#define SYSREG_DRAM_CLK_EN_FD_S		(0)
#define SYSREG_DRAM_CLK_EN_MASK		(1 << SYSREG_DRAM_CLK_EN_FD_S)
#define SYSREG_PIN_STATUS_CLSEL__FD_S	(5)
#define SYSREG_PIN_STATUS_CLSEL_MASK	(1 << SYSREG_PIN_STATUS_CLSEL__FD_S)
#define SYSREG_LX_DEFAULT_MHZ		(200)
#define SYSREG_MCKG_FREQ_DIV_FD_S    (0)
#define SYSREG_MCKG_FREQ_DIV_MASK    (0x3 << SYSREG_MCKG_FREQ_DIV_FD_S)

#define SYSREG_MCKG_PHS_SEL_PHS_FD_S	(0)
#define SYSREG_MCKG_PHS_SEL_PHS_MASK	(0x7 << SYSREG_MCKG_PHS_SEL_PHS_FD_S)
#define SYSREG_SYSCLK_CONTROL_SDPLL_FD_S (0)
#ifdef CONFIG_RTL8685
#define SYSREG_SYSCLK_CONTROL_SDPLL_MASK (0x1f << SYSREG_SYSCLK_CONTROL_SDPLL_FD_S)
#elif defined(CONFIG_RTL8685S) || defined(CONFIG_RTL8685SB)
#define SYSREG_SYSCLK_CONTROL_SDPLL_MASK (0x3f << SYSREG_SYSCLK_CONTROL_SDPLL_FD_S)
#endif /* CONFIG_RTL8685 */
#define SYSREG_SYSCLK_CONTROL_OCP1PLL_FD_S (8)
#define SYSREG_SYSCLK_CONTROL_OCP1PLL_MASK (0x1f << SYSREG_SYSCLK_CONTROL_OCP1PLL_FD_S)
#define SYSREG_SYSCLK_CONTROL_OCP0PLL_FD_S (16)
#define SYSREG_SYSCLK_CONTROL_OCP0PLL_MASK (0x1f << SYSREG_SYSCLK_CONTROL_OCP0PLL_FD_S)
#define SYSREG_DDRCKODL_DDRCLM90_TAP_FD_S (16)
#define SYSREG_DDRCKODL_DDRCLM90_TAP_MASK (0x1f << SYSREG_DDRCKODL_DDRCLM90_TAP_FD_S)
#define SYSREG_DDRCKODL_DDRCLM_TAP_FD_S (8)
#define SYSREG_DDRCKODL_DDRCLM_TAP_MASK (0x1f << SYSREG_DDRCKODL_DDRCLM_TAP_FD_S)
#define SYSREG_DDRCKODL_DDRCK_PHS_FD_S (0)
#define SYSREG_DDRCKODL_DDRCK_PHS_MASK (0x1f << SYSREG_DDRCKODL_DDRCK_PHS_FD_S)

#define SYSREG_OCP0_DEFAULT_MHZ		(500)
#define SYSREG_DDRCKODL_REG		(0xB800021c)

#define SYSREG_CMUIPMASK0_REG		(0xB8000300)
#define SYSREG_CMUIPMASK1_REG		(0xB8000304)

#define SYSREG_CMUCTLR_REG		(0xB8000308)
#define SYSREG_CMUCTLR_CMU_MD_FD_S	(6)
#define SYSREG_CMUCTLR_CMU_MD_MASK	(3 << SYSREG_CMUCTLR_CMU_MD_FD_S)
#ifdef CONFIG_RTL8685
#define SYSREG_CMUCTLR_CMU_MD_MANUALLY_SEL (1)
#define SYSREG_CMUCTLR_CMU_MD_DYNAMIC_SEL (3)
#elif defined(CONFIG_RTL8685S) || defined(CONFIG_RTL8685SB)
#define SYSREG_CMUCTLR_CMU_OC0_BUSY				(1<<31)			
#define SYSREG_CMUCTLR_CMU_MD_DISABLED_SEL		(0)
#define SYSREG_CMUCTLR_CMU_MD_ENABLED_SEL		(1)
#define SYSREG_CMUCTLR_CMU_MD_DYNAMIC_SEL 		(2)
#endif
#define SYSREG_CMUCTLR_CMU_CPU0_FREQ_DIV_FD_S	(23)
#define SYSREG_CMUCTLR_CMU_CPU0_FREQ_DIV_MASK	(7 << SYSREG_CMUCTLR_CMU_CPU0_FREQ_DIV_FD_S)
#define SYSREG_CMUCTLR_CMU_CPU1_FREQ_DIV_FD_S	(20)
#define SYSREG_CMUCTLR_CMU_CPU1_FREQ_DIV_MASK	(7 << SYSREG_CMUCTLR_CMU_CPU1_FREQ_DIV_FD_S)
#define SYSREG_CMUCTLR_CMU_LX0_FREQ_DIV_FD_S	(17)
#define SYSREG_CMUCTLR_CMU_LX0_FREQ_DIV_MASK	(7 << SYSREG_CMUCTLR_CMU_LX0_FREQ_DIV_FD_S)
#define SYSREG_CMUCTLR_CMU_LX1_FREQ_DIV_FD_S	(14)
#define SYSREG_CMUCTLR_CMU_LX1_FREQ_DIV_MASK	(7 << SYSREG_CMUCTLR_CMU_LX1_FREQ_DIV_FD_S)
#define SYSREG_CMUCTLR_CMU_LX2_FREQ_DIV_FD_S	(11)
#define SYSREG_CMUCTLR_CMU_LX2_FREQ_DIV_MASK	(7 << SYSREG_CMUCTLR_CMU_LX2_FREQ_DIV_FD_S)
#define SYSREG_CMUCTLR_CMU_LXP_FREQ_DIV_FD_S	(8)
#define SYSREG_CMUCTLR_CMU_LXP_FREQ_DIV_MASK	(7 << SYSREG_CMUCTLR_CMU_LXP_FREQ_DIV_FD_S)

#define SYSREG_CMUSLPIDX_REG		(0xB800030C)
#if defined(CONFIG_RTL8685S) || defined(CONFIG_RTL8685SB)
#define SYSREG_CMUOC0CR_REG			(0xB8000310)
#define SYSREG_CMUOC0CR_AUTO_BZ		(1<<11)
#define SYSREG_CMUOC0CR_SPIF_HS		(1<<10)
#define SYSREG_CMUOC0CR_SE_SPIF		(1<<9)
#define SYSREG_CMUOC0CR_DRAM_HS		(1<<8)
#define SYSREG_CMUOC0CR_SE_SPIF_WK	(1<<7)
#define SYSREG_CMUOC0CR_SE_SPIF_SLP	(1<<6)
#define SYSREG_CMUOC0CR_SE_DRAM_WK	(1<<5)
#define SYSREG_CMUOC0CR_SE_DRAM_SLP	(1<<4)

#define SYSREG_CMULXBR_REG				(0xB8000344)
#define SYSREG_CMULXBR_LX0_BUSY_S		(31)
#endif /* CONFIG_RTL8685S */

#define SYSREG_OCP0_SMALLER_MASK	(16)
#define SYSREG_OCP1_SMALLER_MASK	(8)
#define SYSREG_LX0_SMALLER_MASK		(4)
#define SYSREG_LX1_SMALLER_MASK		(2)
#define SYSREG_LX2_SMALLER_MASK		(1)

#define SYSREG_WDCNTRR				(0xB8003260)
#define SYSREG_WDT_KICK				(1<<31)
#define SYSREG_WDTCTRLR				(0xB8003268)
#define SYSREG_WDT_E					(1<<31)
#define SYSREG_WDT_CLK_SC_MASK	(3<<29)
#define SYSREG_PH1_TO_S				(22)
#define SYSREG_PH1_TO_MASK			(0x1f << SYSREG_PH1_TO_S )
#define SYSREG_PH2_TO_S				(15)
#define SYSREG_PH2_TO_MASK			(0x1f << SYSREG_PH2_TO_S )

#if defined(CONFIG_RTL8685S) || defined(CONFIG_RTL8685SB)
#define SYSREG_SFCR						(0xb8001200)
#define SYSREG_SFCR_SPI_CLK_DIV_S		(29)		
#define SYSREG_SFCR_SPI_CLK_DIV_MASK	(0x7<<SYSREG_SFCR_SPI_CLK_DIV_S)	


#define SYSREG_ANA_DLL_CTRL0		(0xb8000608)
#define SYSREG_ANA_DLL_CTRL1		(0xb800060c)
#define SYSREG_SWR_CTRL1			(0xb800064c)
#define SYSREG_SWR_CTRL2			(0xb8000650)
#define SYSREG_SWR_ANAREG_RDY		(1 << 31)
#define DDR_DELAY_CTRL_REG0			(0xb80015b0)
#define DDR_DELAY_CTRL_REG1			(0xb80015b4)
#define DDR_DELAY_CTRL_REG2			(0xb80015b8)
#define DDR_DELAY_CTRL_REG3			(0xb80015bc)
#endif /* CONFIG_RTL8685S */

/* * Register access macro */
#ifndef REG32
#define REG32(reg)					(*(volatile unsigned int   *)((unsigned int)reg))
#endif
#ifndef REG16
#define REG16(reg)					(*(volatile unsigned short *)((unsigned int)reg))
#endif
#ifndef REG08
#define REG08(reg)					(*(volatile unsigned char  *)((unsigned int)reg))
#endif
#ifndef REG8
#define REG8(reg)   				(*(volatile unsigned char  *)((unsigned int)reg))
#endif
#ifndef WRITE_MEM32
#define WRITE_MEM32(addr, val)   	(*(volatile unsigned int *)   (addr)) = (val)
#endif
#ifndef READ_MEM32
#define READ_MEM32(addr)         		(*(volatile unsigned int *)   (addr))
#endif
#ifndef WRITE_MEM16
#define WRITE_MEM16(addr, val)   	(*(volatile unsigned short *) (addr)) = (val)
#endif
#ifndef READ_MEM16
#define READ_MEM16(addr)         		(*(volatile unsigned short *) (addr))
#endif
#ifndef WRITE_MEM8
#define WRITE_MEM8(addr, val)    	(*(volatile unsigned char *)  (addr)) = (val)
#endif
#ifndef READ_MEM8
#define READ_MEM8(addr)          		(*(volatile unsigned char *)  (addr))
#endif

#endif   /* _BSPCHIP_H */
