#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#
# Copyright (C) 2015 by Tom Ting <tom_ting@realtek.com>
#

obj-y  += clock.o
obj-y  += timer.o
obj-y  += reset.o
obj-y  += dram.o
obj-y  += hwinit.o
